//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace irception.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth
    {
        public long AuthID { get; set; }
        public string Nick { get; set; }
        public string Username { get; set; }
        public string Host { get; set; }
        public Nullable<int> FKNetworkID { get; set; }
        public System.DateTime DateIssued { get; set; }
        public Nullable<int> FKUserID { get; set; }
        public string SUID { get; set; }
        public Nullable<System.DateTime> DateAuthenticated { get; set; }
    
        public virtual Network Network { get; set; }
        public virtual User User { get; set; }
    }
}
