//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace irception.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoNSFW
    {
        public int AutoNSFWID { get; set; }
        public int FKChannelID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public int FKUserIDAddedBy { get; set; }
        public Nullable<int> FKUserIDDeletedBy { get; set; }
        public string Fragment { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual User UserAddedBy { get; set; }
    }
}
