//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace irception.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invite
    {
        public int InviteID { get; set; }
        public int FKUserIDInvitedBy { get; set; }
        public int FKChannelID { get; set; }
        public System.DateTime DateInvited { get; set; }
        public string SUID { get; set; }
        public string Nick { get; set; }
        public string User { get; set; }
        public string Host { get; set; }
        public Nullable<System.DateTime> DateAccepted { get; set; }
        public Nullable<int> FKUserIDAcceptedBy { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual User UserInvitedBy { get; set; }
        public virtual User UserAcceptedBy { get; set; }
    }
}
