//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace irception.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ircbotEntities : DbContext
    {
        public ircbotEntities()
            : base("name=ircbotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<User> Users { get; set; }
        public DbSet<Network> Networks { get; set; }
        public DbSet<Server> Servers { get; set; }
        public DbSet<Channel> Channels { get; set; }
        public DbSet<Line> Lines { get; set; }
        public DbSet<URL> URLs { get; set; }
        public DbSet<URLUpdateHistory> URLUpdateHistories { get; set; }
        public DbSet<Token> Tokens { get; set; }
        public DbSet<Ignore> Ignores { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<Auth> Auths { get; set; }
    }
}
