//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace irception.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinesGroupedDay
    {
        public int FKChannelID { get; set; }
        public System.DateTime Date { get; set; }
        public string Nick { get; set; }
        public int LineCount { get; set; }
        public int LengthSum { get; set; }
    
        public virtual Channel Channel { get; set; }
    }
}
