//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace irception.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int UserAttrID { get; set; }
        public int FKUserID { get; set; }
        public int FKChannelID { get; set; }
        public string Permission1 { get; set; }
        public int FKUserIDGrantedBy { get; set; }
        public System.DateTime DateGranted { get; set; }
        public Nullable<System.DateTime> DateRevoked { get; set; }
        public Nullable<int> FKUserIDRevokedBy { get; set; }
        public string RevokedReason { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual User User { get; set; }
        public virtual User UserGrantedBy { get; set; }
        public virtual User UserRevokedBy { get; set; }
    }
}
