//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace irception.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public long TokenID { get; set; }
        public System.DateTime Started { get; set; }
        public Nullable<System.DateTime> Ended { get; set; }
        public string EndedReason { get; set; }
        public string Token1 { get; set; }
        public string IP { get; set; }
        public int FKUserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
