//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace irception.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class URLUpdateHistory
    {
        public long URLUpdateHistoryID { get; set; }
        public int FKURLID { get; set; }
        public Nullable<System.DateTime> At { get; set; }
    
        public virtual URL URL { get; set; }
    }
}
