//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace irception.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Ignores = new HashSet<Ignore>();
            this.Permissions = new HashSet<Permission>();
            this.Auths = new HashSet<Auth>();
            this.Invitees = new HashSet<Invite>();
            this.Invite = new HashSet<Invite>();
            this.ChannelVisits = new HashSet<ChannelVisit>();
            this.Votes = new HashSet<Vote>();
        }
    
        public int UserID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string Username { get; set; }
        public string PasswordSHA256 { get; set; }
        public Nullable<int> FKUserIDInvitedBy { get; set; }
        public int InviteLevel { get; set; }
    
        public virtual ICollection<Ignore> Ignores { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
        public virtual ICollection<Auth> Auths { get; set; }
        public virtual ICollection<Invite> Invitees { get; set; }
        public virtual ICollection<Invite> Invite { get; set; }
        public virtual ICollection<ChannelVisit> ChannelVisits { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
