//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ircbot.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public Channel()
        {
            this.Lines = new HashSet<Line>();
            this.URLs = new HashSet<URL>();
            this.Ignores = new HashSet<Ignore>();
            this.Permissions = new HashSet<Permission>();
        }
    
        public int ChannelID { get; set; }
        public int FKNetworkID { get; set; }
        public string ChannelName { get; set; }
        public bool InChannel { get; set; }
        public string Slug { get; set; }
    
        public virtual Network Network { get; set; }
        public virtual ICollection<Line> Lines { get; set; }
        public virtual ICollection<URL> URLs { get; set; }
        public virtual ICollection<Ignore> Ignores { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
