//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ircbot.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        public long LineID { get; set; }
        public int FKChannelID { get; set; }
        public System.DateTime At { get; set; }
        public string Nick { get; set; }
        public Nullable<int> Length { get; set; }
    
        public virtual Channel Channel { get; set; }
    }
}
