//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ircbot.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public long SessionID { get; set; }
        public string Nick { get; set; }
        public string NickUserHost { get; set; }
        public Nullable<int> FKChannelID { get; set; }
        public System.DateTime Started { get; set; }
        public Nullable<System.DateTime> Ended { get; set; }
        public string EndedReason { get; set; }
        public string SUID { get; set; }
    
        public virtual Channel Channel { get; set; }
    }
}
